name: Releases

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '.github/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        net-version: [6.0.x]
        target: [win-x64, win-arm, win-arm64, linux-x64, linux-arm, linux-arm64, linux-musl-x64, linux-musl-arm, linux-musl-arm64, osx-x64]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.net-version }}

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore 
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -r ${{ matrix.target }} -p:PublishTrimmed=true -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained true --output ./${{ matrix.target }}
    - uses: "marvinpinto/action-automatic-releases@4edd7a5aabb1bc62e6dc99b3302d587bf3134e20"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ matrix.target }}-latest"
        prerelease: true
        title: "${{ matrix.target }} development build"
        files: |
          ./${{ matrix.target }}/clarin*

  publish-docker:
    runs-on: ubuntu-latest
    steps:
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: luismedel/clarin
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
